from decouple import config

# Get tokens and keys from env.

TOKEN = config("API_TOKEN")

TENOR_KEY = config("TENOR_API_KEY")

RAPID_API_KEY = config("RAPID_API_KEY")

# Spotify credentials

SPOTIFY_CLIENT_SECRET = str(config("SPOTIPY_CLIENT_SECRET", default='', cast=str))

SPOTIFY_CLIENT_ID = str(config("SPOTIPY_CLIENT_ID", default='', cast=str))

# Twitch credentials

TWITCH_CLIENT_ID = config("TWITCH_CLIENT_ID")

TWITCH_CLIENT_SECRET = config("TWITCH_CLIENT_SECRET")

# Twitter credentials

TWITTER_CONSUMER_KEY = config("TWITTER_CONSUMER_KEY")

TWITTER_CONSUMER_SECRET = config("TWITTER_CONSUMER_SECRET")

TWITTER_ACCESS_TOKEN = config("TWITTER_ACCESS_TOKEN")

TWITTER_ACCESS_TOKEN_SECRET = config("TWITTER_ACCESS_TOKEN_SECRET")

TWITTER_BEARER_TOKEN = config("TWITTER_BEARER_TOKEN")

# Default bot config

PREFIX:str  = "Z"

OWNER_ID = 443064096124960779

GUILD_ID = 1005448304374583386

CROWN_ROLE_ID = 1005544779473489981

BOT_ID = 759844892443672586

# MongoDB Config

MDB_SRV = config("MDB_SRV")

DB_NAME = config("DB_NAME")
